# -*- mode: ruby -*-
# vi: set ft=ruby :

#
#	Centos 7 64-bit Linux mit Docker und ghost
#

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  # Create a public network, which generally matched to bridged network.

  # config.vm.network "public_network", ip: "dhcp"
  config.vm.network "forwarded_port", guest:2368, host:2368, auto_correct: true
  for i in 8080..8089
    config.vm.network :forwarded_port, guest: i, host: i
  end
  
  # Share an additional folder to the guest VM.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end
  # Docker Provisioner
  config.vm.provision "docker" do |d|
   d.pull_images "mysql:5.7"
   d.pull_images "ghost:1-alpine"
   d.run "ghost_mysql", image: "mysql:5.7", args: "-e MYSQL_ROOT_PASSWORD=admin -e MYSQL_USER=ghost -e MYSQL_PASSWORD=secret -e MYSQL_DATABASE=ghost --restart=always"
   d.run "ghost", image: "ghost:1-alpine", args: "--link ghost_mysql:mysql -e database__client=mysql -e database__connection__host=ghost_mysql -e database__connection__user=ghost -e database__connection__password=secret -e database__connection__database=ghost -p 2368:2368 --restart=always"
  end
  config.vm.provision "shell", path: "../misc/install_docker-compose.sh"
  config.vm.provision "shell", path: "../misc/add_user.sh"
  config.vm.provision "shell", inline: <<-SHELL
  sudo mkdir docker-compose
  sudo mkdir docker-compose/ghost 
  sudo mkdir docker-compose/wordpress
  sudo mkdir docker-compose/phpmyadmin
  sudo chown -R vagrant:vagrant docker-compose

  sudo yum install net-tools.x86_64 -y
  sudo yum install telnet.x86_64 -y
  sudo yum install mysql -y
SHELL
  config.vm.provision "file", source: "../docker-compose/ghost/docker-compose.yaml", destination: "~/docker-compose/ghost/docker-compose.yaml"
  config.vm.provision "file", source: "../docker-compose/wordpress/docker-compose.yaml", destination: "~/docker-compose/wordpress/docker-compose.yaml"
  config.vm.provision "file", source: "../docker-compose/phpmyadmin/docker-compose.yaml", destination: "~/docker-compose/phpmyadmin/docker-compose.yaml"
end
