# -*- mode: ruby -*-
# vi: set ft=ruby :

#
#	Ubuntu Version 16.x 64-bit Linux mit Docker und ghost
#

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Create a public network, which generally matched to bridged network.
  #config.vm.network "public_network"
  #config.vm.network "forwarded_port", guest:2368, host:2368, auto_correct: true
 
  for i in 9090..9091
    config.vm.network :forwarded_port, guest: i, host: i
  end

  # Share an additional folder to the guest VM.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end

  # Docker Provisioner
  config.vm.provision "docker" do |d|
   d.pull_images "mysql:5.7"
   d.pull_images "mysql:8"
   d.pull_images "httpd"
   d.pull_images "centos:7"
   d.pull_images "phpmyadmin:phpmyadmin"
 
  end
  config.vm.provision "shell", path: "../misc/install_docker-compose.sh"
end
